# Copyright 2025 CrownOps Engineering
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CLI-specific fixtures shared across unit tests."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from ratchetr._infra.paths import EnvOverrides, ResolvedPaths
from ratchetr.cli.helpers import CLIContext
from ratchetr.config import Config

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

    from ratchetr.core.summary_types import SummaryData
    from ratchetr.core.types import RunResult
    from tests.fixtures.builders import TestDataBuilder


@pytest.fixture
def cli_summary(test_data_builder: TestDataBuilder) -> SummaryData:
    """Provide a reusable sample summary for CLI helper tests.

    Returns:
        Sample `SummaryData` structure used by CLI unit tests.
    """
    return test_data_builder.build_cli_summary()


@pytest.fixture
def cli_run_result(test_data_builder: TestDataBuilder) -> RunResult:
    """Provide a representative RunResult for CLI helper tests.

    Returns:
        `RunResult` generated by the shared data builder.
    """
    return test_data_builder.build_cli_run_result()


def _build_resolved_paths(base_dir: Path) -> ResolvedPaths:
    repo_root = base_dir
    tool_home = repo_root / ".ratchetr"
    cache_dir = tool_home / ".cache"
    log_dir = tool_home / "logs"
    manifest_path = tool_home / "manifest.json"
    dashboard_path = tool_home / "dashboard.html"
    for path in (tool_home, cache_dir, log_dir):
        path.mkdir(parents=True, exist_ok=True)
    manifest_path.touch()
    return ResolvedPaths(
        repo_root=repo_root,
        tool_home=tool_home,
        cache_dir=cache_dir,
        log_dir=log_dir,
        manifest_path=manifest_path,
        dashboard_path=dashboard_path,
        config_path=None,
    )


@pytest.fixture
def cli_context(tmp_path: Path) -> CLIContext:
    """Provide a minimal CLI context rooted in a temporary directory.

    Returns:
        CLIContext: Resolved context scoped to the provided temporary path.
    """
    resolved = _build_resolved_paths(tmp_path)
    return CLIContext(
        config=Config(),
        config_path=None,
        resolved_paths=resolved,
        env_overrides=EnvOverrides.from_environ(),
    )


@pytest.fixture
def cli_context_factory(tmp_path: Path) -> Callable[[Config | None, Path | None], CLIContext]:
    """Factory fixture to build CLI contexts with a custom configuration.

    Args:
        tmp_path: Path to temporary storage.

    Returns:
        Callable[[Config | None, Path | None], CLIContext]: Builder that constructs CLI contexts.
    """

    def _factory(config: Config | None = None, base_dir: Path | None = None) -> CLIContext:
        resolved = _build_resolved_paths(base_dir or tmp_path)
        return CLIContext(
            config=config or Config(),
            config_path=None,
            resolved_paths=resolved,
            env_overrides=EnvOverrides.from_environ(),
        )

    return _factory
